# Generated by Django 4.2.16 on 2026-05-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chakra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="ნომერი")),
                (
                    "name_ge",
                    models.CharField(max_length=255, verbose_name="სახელი (GE)"),
                ),
                ("name_en", models.CharField(max_length=255, verbose_name="Name (EN)")),
                (
                    "theme_ge",
                    models.CharField(max_length=255, verbose_name="თემა (GE)"),
                ),
                (
                    "theme_en",
                    models.CharField(max_length=255, verbose_name="Theme (EN)"),
                ),
                ("conditions_ge", models.TextField(verbose_name="მდგომარეობები (GE)")),
                ("conditions_en", models.TextField(verbose_name="Conditions (EN)")),
                (
                    "color",
                    models.CharField(
                        default="#e91e63", max_length=20, verbose_name="ფერი"
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="🧩", max_length=10, verbose_name="იკონი"),
                ),
            ],
            options={
                "verbose_name": "ჩაკრა",
                "verbose_name_plural": "ჩაკრები",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        default="+995 597 71 84 67",
                        max_length=50,
                        verbose_name="WhatsApp",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        default="@wonderlanderr",
                        max_length=100,
                        verbose_name="Telegram",
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        default="wonderlanderwellness",
                        max_length=100,
                        verbose_name="Instagram",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="dr.guranda8@gmail.com",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "bank_accounts_ge",
                    models.TextField(
                        blank=True, verbose_name="საბანკო რეკვიზიტები (GE)"
                    ),
                ),
                (
                    "bank_accounts_en",
                    models.TextField(blank=True, verbose_name="Bank Details (EN)"),
                ),
            ],
            options={
                "verbose_name": "საკონტაქტო ინფორმაცია",
                "verbose_name_plural": "საკონტაქტო ინფორმაცია",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ge",
                    models.CharField(max_length=255, verbose_name="სათაური (GE)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Title (EN)"),
                ),
                (
                    "subtitle_ge",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="ქვეტექსტი (GE)"
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Subtitle (EN)"
                    ),
                ),
                ("description_ge", models.TextField(verbose_name="აღწერა (GE)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                (
                    "what_you_learn_ge",
                    models.TextField(blank=True, verbose_name="რას ისწავლი (GE)"),
                ),
                (
                    "what_you_learn_en",
                    models.TextField(blank=True, verbose_name="What You'll Learn (EN)"),
                ),
                (
                    "bonuses_ge",
                    models.TextField(blank=True, verbose_name="ბონუსები (GE)"),
                ),
                (
                    "bonuses_en",
                    models.TextField(blank=True, verbose_name="Bonuses (EN)"),
                ),
                (
                    "discount_code",
                    models.CharField(
                        default="888", max_length=50, verbose_name="ფასდაკლების კოდი"
                    ),
                ),
                (
                    "bank_accounts",
                    models.TextField(blank=True, verbose_name="საბანკო ანგარიშები"),
                ),
                (
                    "registration_form_url",
                    models.URLField(blank=True, verbose_name="გარე ფორმის ბმული"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="აქტიური"),
                ),
            ],
            options={
                "verbose_name": "კურსი",
                "verbose_name_plural": "კურსები",
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="სახელი, გვარი"),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="ტელ. ნომერი")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("session", "ინდივიდუალური სესია"),
                            ("course", "კურსი - ფემინური სიმდიდრე"),
                            ("retreat", "ბალის რიტრიტი"),
                            ("mentoring", "მენტორობა"),
                        ],
                        max_length=50,
                        verbose_name="სერვისი",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="შეტყობინება")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="გამოგზავნილია"
                    ),
                ),
            ],
            options={
                "verbose_name": "რეგისტრაცია",
                "verbose_name_plural": "რეგისტრაციები",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Retreat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ge",
                    models.CharField(max_length=255, verbose_name="სათაური (GE)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Title (EN)"),
                ),
                ("date_range", models.CharField(max_length=255, verbose_name="თარიღი")),
                (
                    "location_ge",
                    models.CharField(max_length=255, verbose_name="ადგილი (GE)"),
                ),
                (
                    "location_en",
                    models.CharField(max_length=255, verbose_name="Location (EN)"),
                ),
                ("price", models.CharField(max_length=100, verbose_name="ფასი")),
                (
                    "early_bird_price",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Early Bird ფასი"
                    ),
                ),
                ("description_ge", models.TextField(verbose_name="აღწერა (GE)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                (
                    "includes_ge",
                    models.TextField(blank=True, verbose_name="ფასში შედის (GE)"),
                ),
                (
                    "includes_en",
                    models.TextField(blank=True, verbose_name="Included (EN)"),
                ),
                (
                    "bank_accounts",
                    models.TextField(blank=True, verbose_name="საბანკო ანგარიშები"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="აქტიური"),
                ),
            ],
            options={
                "verbose_name": "რიტრიტი / მოგზაურობა",
                "verbose_name_plural": "რიტრიტები / მოგზაურობები",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ge",
                    models.CharField(max_length=255, verbose_name="სათაური (GE)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Title (EN)"),
                ),
                ("description_ge", models.TextField(verbose_name="აღწერა (GE)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                (
                    "price",
                    models.CharField(max_length=100, verbose_name="ფასი/ინვესტიცია"),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ხანგრძლივობა",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🧩", max_length=10, verbose_name="იკონი (emoji)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="აქტიური"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="თანმიმდევრობა"
                    ),
                ),
            ],
            options={
                "verbose_name": "სერვისი",
                "verbose_name_plural": "სერვისები",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title_ge",
                    models.CharField(default="Wonderlander Wellness", max_length=255),
                ),
                (
                    "site_title_en",
                    models.CharField(default="Wonderlander Wellness", max_length=255),
                ),
                (
                    "hero_title_ge",
                    models.CharField(
                        default="ინდივიდუალურ სესიაზე რეგისტრაცია", max_length=500
                    ),
                ),
                (
                    "hero_title_en",
                    models.CharField(
                        default="Individual Session Registration", max_length=500
                    ),
                ),
                (
                    "hero_subtitle_ge",
                    models.TextField(
                        default="გამარჯობა. პირველ რიგში, მადლობა ნდობისთვის ☀️"
                    ),
                ),
                (
                    "hero_subtitle_en",
                    models.TextField(
                        default="Hello. First of all, thank you for your trust ☀️"
                    ),
                ),
                (
                    "about_text_ge",
                    models.TextField(blank=True, verbose_name="ჩემს შესახებ (GE)"),
                ),
                (
                    "about_text_en",
                    models.TextField(blank=True, verbose_name="About Me (EN)"),
                ),
                (
                    "credentials_ge",
                    models.TextField(blank=True, verbose_name="კვალიფიკაცია (GE)"),
                ),
                (
                    "credentials_en",
                    models.TextField(blank=True, verbose_name="Credentials (EN)"),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="hero/"),
                ),
            ],
            options={
                "verbose_name": "საიტის პარამეტრები",
                "verbose_name_plural": "საიტის პარამეტრები",
            },
        ),
        migrations.CreateModel(
            name="RetreatDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField(verbose_name="დღე №")),
                (
                    "date_label",
                    models.CharField(
                        max_length=100, verbose_name="თარიღი (მაგ: 11 სექტემბერი)"
                    ),
                ),
                (
                    "title_ge",
                    models.CharField(max_length=255, verbose_name="სათაური (GE)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Title (EN)"),
                ),
                ("content_ge", models.TextField(verbose_name="პროგრამა (GE)")),
                ("content_en", models.TextField(verbose_name="Program (EN)")),
                (
                    "retreat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="core.retreat",
                    ),
                ),
            ],
            options={
                "verbose_name": "პროგრამის დღე",
                "verbose_name_plural": "პროგრამის დღეები",
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="CoursePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ge",
                    models.CharField(max_length=100, verbose_name="სახელი (GE)"),
                ),
                ("name_en", models.CharField(max_length=100, verbose_name="Name (EN)")),
                ("price", models.CharField(max_length=100, verbose_name="ფასი")),
                ("features_ge", models.TextField(verbose_name="შეიცავს (GE)")),
                ("features_en", models.TextField(verbose_name="Includes (EN)")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="გამოსაყოფი"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "კურსის პაკეტი",
                "verbose_name_plural": "კურსის პაკეტები",
                "ordering": ["order"],
            },
        ),
    ]
