# Generated by Django 6.0.5 on 2026-05-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chakra",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="chakras/", verbose_name="ფოტო"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="courses/", verbose_name="ფოტო"
            ),
        ),
        migrations.AddField(
            model_name="retreat",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="retreats/", verbose_name="ფოტო"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="services/", verbose_name="ფოტო"
            ),
        ),
    ]
