# Generated by Django 6.0.5 on 2026-05-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_chakra_image_course_image_retreat_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="credentials_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="credentials_ge",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_image",
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="bank_iban_label",
            field=models.CharField(
                default="IBAN", max_length=50, verbose_name="IBAN ლეიბლი"
            ),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="bank_recipient_label_ge",
            field=models.CharField(
                default="მიმღები", max_length=100, verbose_name="მიმღების ლეიბლი (GE)"
            ),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="bank_recipient_name",
            field=models.CharField(
                default="გურანდა ლაზარაშვილი",
                max_length=255,
                verbose_name="მიმღების სახელი",
            ),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="bank_swift_label",
            field=models.CharField(
                default="SWIFT", max_length=50, verbose_name="SWIFT ლეიბლი"
            ),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="bank_title_ge",
            field=models.CharField(
                default="საბანკო რეკვიზიტები",
                max_length=100,
                verbose_name="ბანკის სათაური (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title_en",
            field=models.CharField(
                default="Guranda Lazarashvili",
                max_length=255,
                verbose_name="About Title (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title_ge",
            field=models.CharField(
                default="გურანდა ლაზარაშვილი",
                max_length=255,
                verbose_name="შესახებ სათაური (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="chakras_title_en",
            field=models.CharField(
                default="When Should You Contact Me?",
                max_length=255,
                verbose_name="Chakras Title (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="chakras_title_ge",
            field=models.CharField(
                default="რა მდგომარეობის დროს მომმართოთ?",
                max_length=255,
                verbose_name="ჩაკრების სათაური (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_copy_en",
            field=models.CharField(
                default="© 2024 Wonderlander Wellness. All rights reserved.",
                max_length=255,
                verbose_name="Footer (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_copy_ge",
            field=models.CharField(
                default="© 2024 Wonderlander Wellness. ყველა უფლება დაცულია.",
                max_length=255,
                verbose_name="ფუტერი (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_badge_en",
            field=models.CharField(
                default="✦ WONDERLANDER WELLNESS",
                max_length=100,
                verbose_name="Hero Badge (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_badge_ge",
            field=models.CharField(
                default="✦ WONDERLANDER WELLNESS",
                max_length=100,
                verbose_name="Hero Badge (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn1_en",
            field=models.CharField(
                default="Book Now ❣️", max_length=50, verbose_name="Hero Button 1 (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn1_ge",
            field=models.CharField(
                default="ჩაწერა ❣️", max_length=50, verbose_name="Hero ღილაკი 1 (GE)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn2_en",
            field=models.CharField(
                default="Services", max_length=50, verbose_name="Hero Button 2 (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn2_ge",
            field=models.CharField(
                default="სერვისები", max_length=50, verbose_name="Hero ღილაკი 2 (GE)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="navbar_cta_en",
            field=models.CharField(
                default="Book Now", max_length=50, verbose_name="ნავბარის ღილაკი (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="navbar_cta_ge",
            field=models.CharField(
                default="ჩაწერა", max_length=50, verbose_name="ნავბარის ღილაკი (GE)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="services_title_en",
            field=models.CharField(
                default="Invest in Yourself",
                max_length=255,
                verbose_name="Services Title (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="services_title_ge",
            field=models.CharField(
                default="ინვესტიცია საკუთარ თავში",
                max_length=255,
                verbose_name="სერვისების სათაური (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_subtitle_en",
            field=models.TextField(
                default="Hello. Thank you for your trust ☀️",
                verbose_name="Hero Subtitle (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_subtitle_ge",
            field=models.TextField(
                default="გამარჯობა. მადლობა ნდობისთვის ☀️",
                verbose_name="Hero ქვესათაური (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_en",
            field=models.TextField(
                default="Harmonious relationship with yourself",
                verbose_name="Hero Title (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_ge",
            field=models.TextField(
                default="საკუთარ თავთან ჰარმონიული ურთიერთობა",
                verbose_name="Hero სათაური (GE)",
            ),
        ),
    ]
