# Generated by Django 6.0.5 on 2026-05-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_sitesettings_credentials_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_text_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_title_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="chakras_title_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="footer_copy_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_badge_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_btn1_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_btn2_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_subtitle_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_title_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="services_title_en",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_creds_ge",
            field=models.CharField(
                default="🎓 MD, 🧠 NLP, 🌿 Holistic, 🔥 Kundalini",
                help_text="მძიმით გამოყოფილი",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="intro_tags_ge",
            field=models.TextField(
                default="ფსიქო-სომატიკა, NLP, ჰიპნოთერაპია, კუნდალინი, EFT, არტ თერაპია, იოგა, მედიტაცია"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_contact_ge",
            field=models.CharField(default="კონტაქტი", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_course_ge",
            field=models.CharField(default="ფემინური სიმდიდრე", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_home_ge",
            field=models.CharField(default="მთავარი", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_retreat_ge",
            field=models.CharField(default="ბალი", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat1_label_ge",
            field=models.CharField(default="უფრო სწრაფი შედეგი", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat1_num",
            field=models.CharField(default="10x", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat2_label_ge",
            field=models.CharField(default="სესია მიზნისთვის", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat2_num",
            field=models.CharField(default="1-5", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat3_label_ge",
            field=models.CharField(default="ენერგეტ. ცენტრი", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat3_num",
            field=models.CharField(default="7", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat4_label_ge",
            field=models.CharField(default="სამოქმ. გეგმა", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat4_num",
            field=models.CharField(default="💎", max_length=20),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="about_title_ge",
            field=models.CharField(default="გურანდა ლაზარაშვილი", max_length=255),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="chakras_title_ge",
            field=models.CharField(
                default="რა მდგომარეობის დროს მომმართოთ?", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_copy_ge",
            field=models.CharField(
                default="© 2024 Wonderlander Wellness. ყველა უფლება დაცულია.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_badge_ge",
            field=models.CharField(default="✦ WONDERLANDER WELLNESS", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_btn1_ge",
            field=models.CharField(default="ჩაწერა ❣️", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_btn2_ge",
            field=models.CharField(default="სერვისები", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_subtitle_ge",
            field=models.TextField(default="გამარჯობა. მადლობა ნდობისთვის ☀️"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_ge",
            field=models.TextField(default="საკუთარ თავთან ჰარმონიული ურთიერთობა"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="services_title_ge",
            field=models.CharField(default="ინვესტიცია საკუთარ თავში", max_length=255),
        ),
    ]
