# Generated by Django 6.0.5 on 2026-05-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_sitesettings_about_text_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/",
                verbose_name="პროფილის (About) ფოტო",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/",
                verbose_name="მთავარი (Hero) ფოტო",
            ),
        ),
    ]
