# Generated by Django 6.0.5 on 2026-05-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_sitesettings_about_image_sitesettings_hero_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="short_description_en",
            field=models.CharField(
                blank=True,
                help_text="1-2 sentences shown on listing. Empty = auto-truncated.",
                max_length=300,
                verbose_name="Short Description - on card (EN)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="short_description_ge",
            field=models.CharField(
                blank=True,
                help_text="1-2 წინადადება. ჩამოთვლის გვერდზე გამოჩნდება. ცარიელი = ავტო-შემოკლება.",
                max_length=300,
                verbose_name="მოკლე აღწერა - კარტზე (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description_en",
            field=models.TextField(
                verbose_name="Full Description - on detail page (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description_ge",
            field=models.TextField(verbose_name="სრული აღწერა - დეტალებზე (GE)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="nav_course_ge",
            field=models.CharField(default="კურსები", max_length=50),
        ),
    ]
