# Generated by Django 6.0.5 on 2026-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_service_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_text_en",
            field=models.TextField(blank=True, verbose_name="About Me (EN)"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title_en",
            field=models.CharField(
                blank=True, default="Guranda Lazarashvili", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="chakras_title_en",
            field=models.CharField(
                blank=True, default="When Should You Contact Me?", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_copy_en",
            field=models.CharField(
                blank=True,
                default="© 2024 Wonderlander Wellness. All rights reserved.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_badge_en",
            field=models.CharField(
                blank=True, default="✦ WONDERLANDER WELLNESS", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn1_en",
            field=models.CharField(blank=True, default="Book Now ❣️", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_btn2_en",
            field=models.CharField(blank=True, default="Services", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_creds_en",
            field=models.CharField(
                blank=True,
                default="🎓 MD, 🧠 NLP, 🌿 Holistic, 🔥 Kundalini",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_subtitle_en",
            field=models.TextField(
                blank=True, default="Hello. Thank you for your trust ☀️"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_title_en",
            field=models.TextField(
                blank=True, default="Harmonious Relationship With Yourself"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="intro_tags_en",
            field=models.TextField(
                blank=True,
                default="Psycho-somatics, NLP, Hypnotherapy, Kundalini, EFT, Art Therapy, Yoga, Meditation",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_contact_en",
            field=models.CharField(blank=True, default="Contact", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_course_en",
            field=models.CharField(blank=True, default="Courses", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_home_en",
            field=models.CharField(blank=True, default="Home", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_retreat_en",
            field=models.CharField(blank=True, default="Retreats", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="services_title_en",
            field=models.CharField(
                blank=True, default="Investment In Yourself", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat1_label_en",
            field=models.CharField(
                blank=True, default="Faster Results", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat2_label_en",
            field=models.CharField(
                blank=True, default="Sessions for Goal", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat3_label_en",
            field=models.CharField(
                blank=True, default="Energy Centers", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat4_label_en",
            field=models.CharField(blank=True, default="Action Plan", max_length=100),
        ),
    ]
