# Generated by Django 6.0.5 on 2026-05-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_en_site_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="chakra",
            name="description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description (EN)"
            ),
        ),
        migrations.AddField(
            model_name="chakra",
            name="description_ge",
            field=models.TextField(blank=True, null=True, verbose_name="აღწერა (GE)"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("session", "ინდივიდუალური სესია / Individual Session"),
                    ("course", "კურსები / Courses"),
                    ("retreat", "ბალის რიტრიტი / Bali Retreat"),
                    ("mentoring", "მენტორობა / Mentoring"),
                ],
                max_length=50,
                verbose_name="სერვისი",
            ),
        ),
    ]
