# Generated by Django 6.0.5 on 2026-05-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_chakra_description_en_chakra_description_ge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="packages_title_en",
            field=models.CharField(
                default="Choose Your Package",
                max_length=255,
                verbose_name="Packages Section Title (EN)",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="packages_title_ge",
            field=models.CharField(
                default="აირჩიე შენი პაკეტი",
                max_length=255,
                verbose_name="პაკეტების სექციის სათაური (GE)",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="total_value_en",
            field=models.CharField(
                default="2688 ₾", max_length=100, verbose_name="Total Value (EN)"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="total_value_ge",
            field=models.CharField(
                default="2688 ₾", max_length=100, verbose_name="ჯამური ღირებულება (GE)"
            ),
        ),
    ]
