# Generated by Django 6.0.5 on 2026-05-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_course_packages_title_en_course_packages_title_ge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="bank_recipient_label_en",
            field=models.CharField(
                default="Recipient", max_length=100, verbose_name="Recipient Label (EN)"
            ),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="bank_recipient_name_en",
            field=models.CharField(
                default="Guranda Lazarashvili",
                max_length=255,
                verbose_name="Recipient Name (EN)",
            ),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="bank_title_en",
            field=models.CharField(
                default="Bank Details", max_length=100, verbose_name="Bank Title (EN)"
            ),
        ),
        migrations.AddField(
            model_name="retreatday",
            name="date_label_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Date Label (EN) (e.g. 11 Sep)"
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="bank_recipient_name",
            field=models.CharField(
                default="გურანდა ლაზარაშვილი",
                max_length=255,
                verbose_name="მიმღების სახელი (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_copy_en",
            field=models.CharField(
                blank=True,
                default="© 2026 Wonderlander Wellness. All rights reserved.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_copy_ge",
            field=models.CharField(
                default="© 2026 Wonderlander Wellness. ყველა უფლება დაცულია.",
                max_length=255,
            ),
        ),
    ]
