# Generated by Django 6.0.5 on 2026-05-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_contactinfo_bank_recipient_label_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="label_book_session_en",
            field=models.CharField(
                default="Book a Session",
                max_length=100,
                verbose_name="Title 'Book a Session' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_book_session_ge",
            field=models.CharField(
                default="დაჯავშნე სესია",
                max_length=100,
                verbose_name="სათაური 'დაჯავშნე სესია' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_booking_en",
            field=models.CharField(
                default="Booking", max_length=50, verbose_name="Title 'Booking' (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_booking_ge",
            field=models.CharField(
                default="დაჯავშნა",
                max_length=50,
                verbose_name="სათაური 'დაჯავშნა' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_choose_course_en",
            field=models.CharField(
                default="Choose the course that's right for you",
                max_length=255,
                verbose_name="Subtitle 'Choose Course' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_choose_course_ge",
            field=models.CharField(
                default="აირჩიეთ თქვენთვის შესაფერი კურსი",
                max_length=255,
                verbose_name="ქვესათაური 'აირჩიეთ კურსი' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_course_en",
            field=models.CharField(
                default="Course", max_length=50, verbose_name="Badge 'Course' (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_course_ge",
            field=models.CharField(
                default="კურსი", max_length=50, verbose_name="ბეიჯი 'კურსი' (GE)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_details_en",
            field=models.CharField(
                default="Details →", max_length=50, verbose_name="Button 'Details' (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_details_ge",
            field=models.CharField(
                default="დეტალურად →",
                max_length=50,
                verbose_name="ღილაკი 'დეტალურად' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_guarantee_en",
            field=models.CharField(
                default="110% Money-back Guarantee",
                max_length=100,
                verbose_name="Guarantee Text (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_guarantee_ge",
            field=models.CharField(
                default="110% თანხის დაბრუნების გარანტია",
                max_length=100,
                verbose_name="გარანტიის ტექსტი (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_let_start_en",
            field=models.CharField(
                default="Let's Start ❣️",
                max_length=50,
                verbose_name="Button 'Let's Start' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_let_start_ge",
            field=models.CharField(
                default="დავიწყოთ ❣️",
                max_length=50,
                verbose_name="ღილაკი 'დავიწყოთ' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_our_courses_en",
            field=models.CharField(
                default="Our Courses",
                max_length=100,
                verbose_name="Title 'Our Courses' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_our_courses_ge",
            field=models.CharField(
                default="ჩვენი კურსები",
                max_length=100,
                verbose_name="სათაური 'ჩვენი კურსები' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_popular_en",
            field=models.CharField(
                default="Popular", max_length=50, verbose_name="Badge 'Popular' (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_popular_ge",
            field=models.CharField(
                default="პოპულარული",
                max_length=50,
                verbose_name="ბეიჯი 'პოპულარული' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_save_en",
            field=models.CharField(
                default="Save", max_length=50, verbose_name="Text 'Save' (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_save_ge",
            field=models.CharField(
                default="დაზოგე", max_length=50, verbose_name="ტექსტი 'დაზოგე' (GE)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_submit_app_en",
            field=models.CharField(
                default="Submit Application 🔥",
                max_length=100,
                verbose_name="Button 'Submit' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_submit_app_ge",
            field=models.CharField(
                default="განაცხადის გაგზავნა 🔥",
                max_length=100,
                verbose_name="ღილაკი 'განაცხადის გაგზავნა' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_total_value_en",
            field=models.CharField(
                default="Total Value",
                max_length=100,
                verbose_name="Text 'Total Value' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_total_value_ge",
            field=models.CharField(
                default="ჯამური ღირებულება",
                max_length=100,
                verbose_name="ტექსტი 'ჯამური ღირებულება' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_what_learn_en",
            field=models.CharField(
                default="What You'll Learn",
                max_length=100,
                verbose_name="Title 'What You'll Learn' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_what_learn_ge",
            field=models.CharField(
                default="რას ისწავლი?",
                max_length=100,
                verbose_name="სათაური 'რას ისწავლი' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_you_feel_en",
            field=models.CharField(
                default="You feel...",
                max_length=100,
                verbose_name="Title 'You feel' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_you_feel_ge",
            field=models.CharField(
                default="შენ გრძნობ...",
                max_length=100,
                verbose_name="სათაური 'შენ გრძნობ' (GE)",
            ),
        ),
    ]
