# Generated by Django 6.0.5 on 2026-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_sitesettings_label_book_session_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ge",
                    models.CharField(max_length=100, verbose_name="სახელი (GE)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (EN)"
                    ),
                ),
                ("text_ge", models.TextField(verbose_name="ტექსტი (GE)")),
                ("text_en", models.TextField(blank=True, verbose_name="Text (EN)")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=5, verbose_name="შეფასება (1-5)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="reviews/", verbose_name="ფოტო"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="აქტიური"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="თანმიმდევრობა"
                    ),
                ),
            ],
            options={
                "verbose_name": "უკუკავშირი",
                "verbose_name_plural": "უკუკავშირები",
                "ordering": ["order", "-id"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_review_en",
            field=models.CharField(blank=True, default="Reviews", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_review_ge",
            field=models.CharField(default="უკუკავშირი", max_length=50),
        ),
    ]
