# Generated by Django 6.0.5 on 2026-06-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_review_sitesettings_nav_review_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="reviews_empty_text_en",
            field=models.CharField(
                blank=True, default="No reviews added yet.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="reviews_empty_text_ge",
            field=models.CharField(
                default="უკუკავშირები ჯერ არ დამატებულა.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="reviews_title_en",
            field=models.CharField(blank=True, default="What They Say", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="reviews_title_ge",
            field=models.CharField(default="რას ამბობენ ჩვენზე", max_length=255),
        ),
    ]
