# Generated by Django 6.0.5 on 2026-06-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_sitesettings_reviews_empty_text_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retreat",
            name="date_range",
        ),
        migrations.AddField(
            model_name="retreat",
            name="date_range_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Date (EN)"
            ),
        ),
        migrations.AddField(
            model_name="retreat",
            name="date_range_ge",
            field=models.CharField(
                default="", max_length=255, verbose_name="თარიღი (GE)"
            ),
        ),
        migrations.AddField(
            model_name="retreat",
            name="disclaimer_en",
            field=models.CharField(
                blank=True,
                default="* Price excludes flight tickets",
                max_length=255,
                verbose_name="Disclaimer (EN)",
            ),
        ),
        migrations.AddField(
            model_name="retreat",
            name="disclaimer_ge",
            field=models.CharField(
                blank=True,
                default="* ფასში არ შედის ავიაბილეთები",
                max_length=255,
                verbose_name="შენიშვნა (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_early_bird_en",
            field=models.CharField(
                default="Early Bird",
                max_length=50,
                verbose_name="Title 'Early Bird' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_early_bird_ge",
            field=models.CharField(
                default="Early Bird",
                max_length=50,
                verbose_name="სათაური 'Early Bird' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_included_en",
            field=models.CharField(
                default="What's Included",
                max_length=100,
                verbose_name="Title 'What's Included' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_included_ge",
            field=models.CharField(
                default="ღირებულებაში შედის",
                max_length=100,
                verbose_name="სათაური 'ღირებულებაში შედის' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_program_en",
            field=models.CharField(
                default="Program", max_length=100, verbose_name="Title 'Program' (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_program_ge",
            field=models.CharField(
                default="პროგრამა",
                max_length=100,
                verbose_name="სათაური 'პროგრამა' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_regular_price_en",
            field=models.CharField(
                default="Regular",
                max_length=50,
                verbose_name="Title 'Regular Price' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_regular_price_ge",
            field=models.CharField(
                default="რეგულარული",
                max_length=50,
                verbose_name="სათაური 'რეგულარული ფასი' (GE)",
            ),
        ),
    ]
