# Generated by Django 6.0.5 on 2026-06-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_remove_retreat_date_range_retreat_date_range_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_token",
                    models.CharField(max_length=255, verbose_name="Bot Token"),
                ),
                (
                    "admin_chat_id",
                    models.CharField(max_length=100, verbose_name="Admin Chat ID"),
                ),
                (
                    "welcome_text_ge",
                    models.TextField(
                        default="✨ მოგესალმებით Wonderlander Wellness-ში!\n\nაირჩიეთ ნებისმიერი სექცია ქვემოთ ⬇️",
                        verbose_name="მისალმების ტექსტი (GE)",
                    ),
                ),
                (
                    "services_menu_text_ge",
                    models.CharField(
                        default="💫 ჩვენი სერვისები — აირჩიეთ:",
                        max_length=255,
                        verbose_name="სერვისების მენიუს ტექსტი (GE)",
                    ),
                ),
                (
                    "courses_menu_text_ge",
                    models.CharField(
                        default="📚 ჩვენი კურსები — აირჩიეთ:",
                        max_length=255,
                        verbose_name="კურსების მენიუს ტექსტი (GE)",
                    ),
                ),
                (
                    "contact_text_ge",
                    models.TextField(
                        default="📍 <b>კონტაქტი</b>\n\n📧 dr.guranda8@gmail.com",
                        verbose_name="კონტაქტის ტექსტი (GE)",
                    ),
                ),
                (
                    "booking_success_text_ge",
                    models.TextField(
                        default="🎉 <b>განაცხადი მიღებულია!</b>\n\nგურანდა მალე დაგიკავშირდებათ! ✨",
                        verbose_name="ჯავშნის დასრულების ტექსტი (GE)",
                    ),
                ),
            ],
            options={
                "verbose_name": "ბოტის პარამეტრები",
                "verbose_name_plural": "ბოტის პარამეტრები",
            },
        ),
    ]
