# Generated by Django 6.0.5 on 2026-06-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_botsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="botsettings",
            name="booking_admin_notify",
            field=models.TextField(
                default="🔔 <b>ახალი განაცხადი ბოტიდან!</b>",
                verbose_name="ადმინის შეტყობინების სათაური",
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="booking_ask_name",
            field=models.TextField(
                default="📝 <b>ჩაწერის ფორმა</b>\n\nგთხოვთ, შეიყვანეთ თქვენი <b>სახელი და გვარი</b>:",
                verbose_name="ჯავშანი: სახელის მოთხოვნა",
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="booking_ask_phone",
            field=models.CharField(
                default="✅ მადლობა!\n\nშეიყვანეთ თქვენი <b>ტელეფონის ნომერი</b> (მაგ: +995599123456):",
                max_length=255,
                verbose_name="ჯავშანი: ნომრის მოთხოვნა",
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="bot_started_text",
            field=models.CharField(
                default="🟢 <b>ბოტი ჩაირთო!</b> Wonderlander Wellness Bot is running.",
                max_length=255,
                verbose_name="ბოტის ჩართვის შეტყობინება",
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="btn_back",
            field=models.CharField(
                default="🔙 უკან", max_length=100, verbose_name="ღილაკი: უკან"
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="btn_booking",
            field=models.CharField(
                default="📅 ჩაწერა", max_length=100, verbose_name="ღილაკი: ჩაწერა"
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="btn_contact",
            field=models.CharField(
                default="📞 კონტაქტი", max_length=100, verbose_name="ღილაკი: კონტაქტი"
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="btn_courses",
            field=models.CharField(
                default="📚 კურსები", max_length=100, verbose_name="ღილაკი: კურსები"
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="btn_language",
            field=models.CharField(
                default="🌐 ენა / Language", max_length=100, verbose_name="ღილაკი: ენა"
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="btn_language_en",
            field=models.CharField(
                default="🇬🇧 English",
                max_length=100,
                verbose_name="ღილაკი: ინგლისური ენა",
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="btn_language_ge",
            field=models.CharField(
                default="🇬🇪 ქართული", max_length=100, verbose_name="ღილაკი: ქართული ენა"
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="btn_pay_label",
            field=models.CharField(
                default="💳 გადახდა", max_length=100, verbose_name="ღილაკი: გადახდა"
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="btn_services",
            field=models.CharField(
                default="🌟 სერვისები", max_length=100, verbose_name="ღილაკი: სერვისები"
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="language_choice_text",
            field=models.CharField(
                default="Choose language / ენა:",
                max_length=255,
                verbose_name="ენის არჩევის ტექსტი",
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="not_found_text",
            field=models.CharField(
                default="❌ ინფორმაცია ვერ მოიძებნა",
                max_length=255,
                verbose_name="ვერ მოიძებნა — ტექსტი",
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="payment_soon_text",
            field=models.CharField(
                default="💳 გადახდის სისტემა მალე გაიხსნება!",
                max_length=255,
                verbose_name="გადახდის მიმდინარე ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="booking_success_text_ge",
            field=models.TextField(
                default="🎉 <b>განაცხადი მიღებულია!</b>\n\nგურანდა მალე დაგიკავშირდებათ! ✨",
                verbose_name="ჯავშნის დასრულების ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="contact_text_ge",
            field=models.TextField(
                default="📍 <b>კონტაქტი</b>\n\n📧 dr.guranda8@gmail.com",
                verbose_name="კონტაქტის ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="courses_menu_text_ge",
            field=models.CharField(
                default="📚 ჩვენი კურსები — აირჩიეთ:",
                max_length=255,
                verbose_name="კურსების მენიუს ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="services_menu_text_ge",
            field=models.CharField(
                default="💫 ჩვენი სერვისები — აირჩიეთ:",
                max_length=255,
                verbose_name="სერვისების მენიუს ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="welcome_text_ge",
            field=models.TextField(
                default="✨ მოგესალმებით Wonderlander Wellness-ში!\n\nაირჩიეთ ნებისმიერი სექცია ქვემოთ ⬇️",
                verbose_name="მისალმების ტექსტი",
            ),
        ),
    ]
