# Generated by Django 6.0.5 on 2026-07-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_botsettings_booking_admin_notify_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="label_choose_chakra_en",
            field=models.CharField(
                default="Click on the chakra where you feel the issue",
                max_length=255,
                verbose_name="Subtitle 'Choose Chakra' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_choose_chakra_ge",
            field=models.CharField(
                default="დააჭირეთ ჩაკრას, რომელშიც პრობლემას გრძნობთ",
                max_length=255,
                verbose_name="ქვესათაური 'აირჩიეთ ჩაკრა' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_energy_centers_en",
            field=models.CharField(
                default="Energy Centers",
                max_length=100,
                verbose_name="Badge 'Energy Centers' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_energy_centers_ge",
            field=models.CharField(
                default="ენერგეტიკული ცენტრები",
                max_length=100,
                verbose_name="ბეიჯი 'ენერგეტიკული ცენტრები' (GE)",
            ),
        ),
    ]
