# Generated by Django 6.0.5 on 2026-07-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_sitesettings_label_choose_chakra_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="home_cta_text_en",
            field=models.TextField(
                default="The first step is a session. Results in 1-5 meetings. ❣️",
                verbose_name="Call-to-Action Text (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_cta_text_ge",
            field=models.TextField(
                default="პირველი ნაბიჯი — ეს სესია. შედეგი 1-5 შეხვედრაში. ❣️",
                verbose_name="ქოლ-თუ-ექშენ ტექსტი (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_cta_title_en",
            field=models.CharField(
                default="Ready for Transformation?",
                max_length=255,
                verbose_name="Call-to-Action Title (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_cta_title_ge",
            field=models.CharField(
                default="მზად ხარ ტრანსფორმაციისთვის?",
                max_length=255,
                verbose_name="ქოლ-თუ-ექშენ სათაური (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_why_text1_en",
            field=models.TextField(
                default="Unlike standard psychotherapy, we achieve results 10x faster. Most problems are resolved/goals achieved in 1-5 sessions 🤗",
                verbose_name="Why Work with Me - Text 1 (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_why_text1_ge",
            field=models.TextField(
                default="სტანდარტული ფსიქოთერაპიისგან განსხვავებით, შედეგებს ვიღებთ 10ჯერ უფრო სწრაფად. პრობლემათა უმრავლესობის გადაჭრა/მიზნების მიღწევა ხდება 1-5 სესიაში 🤗",
                verbose_name="რატომ ჩემთან - ტექსტი 1 (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_why_text2_en",
            field=models.TextField(
                default="Instead of exhausting conversations, we use unique methodology — Psycho-somatics, NLP, Hypnotherapy, Kundalini Activation, EFT, Art Therapy.",
                verbose_name="Why Work with Me - Text 2 (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_why_text2_ge",
            field=models.TextField(
                default="სესიაზე დამღლელი საუბრების მაგივრად, ვიყენებთ უნიკალურ მეთოდოლოგიას — ფსიქო-სომატიკა, NLP, ჰიპნოთერაპია, კუნდალინი აქტივაცია, EFT, არტ თერაპია.",
                verbose_name="რატომ ჩემთან - ტექსტი 2 (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_why_title_en",
            field=models.CharField(
                default="Why Work with Me?",
                max_length=255,
                verbose_name="Section 'Why Work with Me' Title (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_why_title_ge",
            field=models.CharField(
                default="რატომ ჩემთან?",
                max_length=255,
                verbose_name="სექცია 'რატომ ჩემთან' სათაური (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_bonuses_en",
            field=models.CharField(
                default="Bonuses", max_length=100, verbose_name="Title 'Bonuses' (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_bonuses_ge",
            field=models.CharField(
                default="ბონუსები",
                max_length=100,
                verbose_name="სათაური 'ბონუსები' (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_book_en",
            field=models.CharField(
                default="Book ❣️",
                max_length=100,
                verbose_name="Button 'Book' (on retreats) (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_book_ge",
            field=models.CharField(
                default="დაჯავშნა ❣️",
                max_length=100,
                verbose_name="ღილაკი 'დაჯავშნა' (რიტრიტებზე) (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_enroll_en",
            field=models.CharField(
                default="Enroll ❣️",
                max_length=100,
                verbose_name="Button 'Enroll' (on courses) (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_enroll_ge",
            field=models.CharField(
                default="ჩაწერა ❣️",
                max_length=100,
                verbose_name="ღილაკი 'ჩაწერა' (კურსებზე) (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_select_en",
            field=models.CharField(
                default="Select",
                max_length=100,
                verbose_name="Button 'Select' (on packages) (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_select_ge",
            field=models.CharField(
                default="არჩევა",
                max_length=100,
                verbose_name="ღილაკი 'არჩევა' (პაკეტებზე) (GE)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_whatsapp_btn_en",
            field=models.CharField(
                default="Message on WhatsApp",
                max_length=100,
                verbose_name="Button 'WhatsApp' (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="label_whatsapp_btn_ge",
            field=models.CharField(
                default="WhatsApp-ზე დაწერა",
                max_length=100,
                verbose_name="ღილაკი 'WhatsApp' (GE)",
            ),
        ),
    ]
