# Generated by Django 6.0.5 on 2026-07-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_remove_emojis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botsettings",
            name="admin_chat_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Admin Chat ID"
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="booking_admin_notify",
            field=models.TextField(
                blank=True,
                default="ახალი განაცხადი ბოტიდან!",
                verbose_name="ადმინის შეტყობინების სათაური",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="booking_ask_name",
            field=models.TextField(
                blank=True,
                default="ჩაწერის ფორმა\n\nგთხოვთ, შეიყვანეთ თქვენი სახელი და გვარი:",
                verbose_name="ჯავშანი: სახელის მოთხოვნა",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="booking_ask_phone",
            field=models.CharField(
                blank=True,
                default="მადლობა!\n\nშეიყვანეთ თქვენი ტელეფონის ნომერი (მაგ: +995599123456):",
                max_length=255,
                verbose_name="ჯავშანი: ნომრის მოთხოვნა",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="booking_success_text_ge",
            field=models.TextField(
                blank=True,
                default="განაცხადი მიღებულია!\n\nგურანდა მალე დაგიკავშირდებათ!",
                verbose_name="ჯავშნის დასრულების ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="bot_started_text",
            field=models.CharField(
                blank=True,
                default="ბოტი ჩაირთო! Wonderlander Wellness Bot is running.",
                max_length=255,
                verbose_name="ბოტის ჩართვის შეტყობინება",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="bot_token",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Bot Token"
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="btn_back",
            field=models.CharField(
                blank=True, default="უკან", max_length=100, verbose_name="ღილაკი: უკან"
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="btn_booking",
            field=models.CharField(
                blank=True,
                default="ჩაწერა",
                max_length=100,
                verbose_name="ღილაკი: ჩაწერა",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="btn_contact",
            field=models.CharField(
                blank=True,
                default="კონტაქტი",
                max_length=100,
                verbose_name="ღილაკი: კონტაქტი",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="btn_courses",
            field=models.CharField(
                blank=True,
                default="კურსები",
                max_length=100,
                verbose_name="ღილაკი: კურსები",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="btn_language",
            field=models.CharField(
                blank=True,
                default="ენა / Language",
                max_length=100,
                verbose_name="ღილაკი: ენა",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="btn_language_en",
            field=models.CharField(
                blank=True,
                default="English",
                max_length=100,
                verbose_name="ღილაკი: ინგლისური ენა",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="btn_language_ge",
            field=models.CharField(
                blank=True,
                default="ქართული",
                max_length=100,
                verbose_name="ღილაკი: ქართული ენა",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="btn_pay_label",
            field=models.CharField(
                blank=True,
                default="გადახდა",
                max_length=100,
                verbose_name="ღილაკი: გადახდა",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="btn_services",
            field=models.CharField(
                blank=True,
                default="სერვისები",
                max_length=100,
                verbose_name="ღილაკი: სერვისები",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="contact_text_ge",
            field=models.TextField(
                blank=True,
                default="კონტაქტი\n\ndr.guranda8@gmail.com",
                verbose_name="კონტაქტის ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="courses_menu_text_ge",
            field=models.CharField(
                blank=True,
                default="ჩვენი კურსები — აირჩიეთ:",
                max_length=255,
                verbose_name="კურსების მენიუს ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="language_choice_text",
            field=models.CharField(
                blank=True,
                default="Choose language / ენა:",
                max_length=255,
                verbose_name="ენის არჩევის ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="not_found_text",
            field=models.CharField(
                blank=True,
                default="ინფორმაცია ვერ მოიძებნა",
                max_length=255,
                verbose_name="ვერ მოიძებნა — ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="payment_soon_text",
            field=models.CharField(
                blank=True,
                default="გადახდის სისტემა მალე გაიხსნება!",
                max_length=255,
                verbose_name="გადახდის მიმდინარე ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="services_menu_text_ge",
            field=models.CharField(
                blank=True,
                default="ჩვენი სერვისები — აირჩიეთ:",
                max_length=255,
                verbose_name="სერვისების მენიუს ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="welcome_text_ge",
            field=models.TextField(
                blank=True,
                default="მოგესალმებით Wonderlander Wellness-ში!\n\nაირჩიეთ ნებისმიერი სექცია ქვემოთ",
                verbose_name="მისალმების ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="chakra",
            name="color",
            field=models.CharField(
                blank=True, default="#e91e63", max_length=20, verbose_name="ფერი"
            ),
        ),
        migrations.AlterField(
            model_name="chakra",
            name="conditions_en",
            field=models.TextField(blank=True, verbose_name="Conditions (EN)"),
        ),
        migrations.AlterField(
            model_name="chakra",
            name="conditions_ge",
            field=models.TextField(blank=True, verbose_name="მდგომარეობები (GE)"),
        ),
        migrations.AlterField(
            model_name="chakra",
            name="icon",
            field=models.CharField(
                blank=True, default="", max_length=10, null=True, verbose_name="იკონი"
            ),
        ),
        migrations.AlterField(
            model_name="chakra",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="chakra",
            name="theme_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Theme (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="chakra",
            name="theme_ge",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="თემა (GE)"
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="bank_iban_label",
            field=models.CharField(
                blank=True, default="IBAN", max_length=50, verbose_name="IBAN ლეიბლი"
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="bank_recipient_label_en",
            field=models.CharField(
                blank=True,
                default="Recipient",
                max_length=100,
                verbose_name="Recipient Label (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="bank_recipient_label_ge",
            field=models.CharField(
                blank=True,
                default="მიმღები",
                max_length=100,
                verbose_name="მიმღების ლეიბლი (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="bank_recipient_name",
            field=models.CharField(
                blank=True,
                default="გურანდა ლაზარაშვილი",
                max_length=255,
                verbose_name="მიმღების სახელი (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="bank_recipient_name_en",
            field=models.CharField(
                blank=True,
                default="Guranda Lazarashvili",
                max_length=255,
                verbose_name="Recipient Name (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="bank_swift_label",
            field=models.CharField(
                blank=True, default="SWIFT", max_length=50, verbose_name="SWIFT ლეიბლი"
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="bank_title_en",
            field=models.CharField(
                blank=True,
                default="Bank Details",
                max_length=100,
                verbose_name="Bank Title (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="bank_title_ge",
            field=models.CharField(
                blank=True,
                default="საბანკო რეკვიზიტები",
                max_length=100,
                verbose_name="ბანკის სათაური (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="email",
            field=models.EmailField(
                blank=True,
                default="dr.guranda8@gmail.com",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="instagram",
            field=models.CharField(
                blank=True,
                default="wonderlanderwellness",
                max_length=100,
                verbose_name="Instagram",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="telegram",
            field=models.CharField(
                blank=True,
                default="@wonderlanderr",
                max_length=100,
                verbose_name="Telegram",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                default="+995 597 71 84 67",
                max_length=50,
                verbose_name="WhatsApp",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (EN)"),
        ),
        migrations.AlterField(
            model_name="course",
            name="description_ge",
            field=models.TextField(blank=True, verbose_name="აღწერა (GE)"),
        ),
        migrations.AlterField(
            model_name="course",
            name="discount_code",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="ფასდაკლების კოდი"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="packages_title_en",
            field=models.CharField(
                blank=True,
                default="Choose Your Package",
                max_length=255,
                verbose_name="Packages Section Title (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="packages_title_ge",
            field=models.CharField(
                blank=True,
                default="აირჩიე შენი პაკეტი",
                max_length=255,
                verbose_name="პაკეტების სექციის სათაური (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Title (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="total_value_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Total Value (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="total_value_ge",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ჯამური ღირებულება (GE)"
            ),
        ),
        migrations.AlterField(
            model_name="coursepackage",
            name="features_en",
            field=models.TextField(blank=True, verbose_name="Includes (EN)"),
        ),
        migrations.AlterField(
            model_name="coursepackage",
            name="features_ge",
            field=models.TextField(blank=True, verbose_name="შეიცავს (GE)"),
        ),
        migrations.AlterField(
            model_name="coursepackage",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Name (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="coursepackage",
            name="price",
            field=models.CharField(blank=True, max_length=100, verbose_name="ფასი"),
        ),
        migrations.AlterField(
            model_name="retreat",
            name="date_range_ge",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="თარიღი (GE)"
            ),
        ),
        migrations.AlterField(
            model_name="retreat",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (EN)"),
        ),
        migrations.AlterField(
            model_name="retreat",
            name="description_ge",
            field=models.TextField(blank=True, verbose_name="აღწერა (GE)"),
        ),
        migrations.AlterField(
            model_name="retreat",
            name="location_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Location (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="retreat",
            name="location_ge",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ადგილი (GE)"
            ),
        ),
        migrations.AlterField(
            model_name="retreat",
            name="price",
            field=models.CharField(blank=True, max_length=100, verbose_name="ფასი"),
        ),
        migrations.AlterField(
            model_name="retreat",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Title (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="retreatday",
            name="content_en",
            field=models.TextField(blank=True, verbose_name="Program (EN)"),
        ),
        migrations.AlterField(
            model_name="retreatday",
            name="content_ge",
            field=models.TextField(blank=True, verbose_name="პროგრამა (GE)"),
        ),
        migrations.AlterField(
            model_name="retreatday",
            name="date_label",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="თარიღი (მაგ: 11 სექტემბერი)"
            ),
        ),
        migrations.AlterField(
            model_name="retreatday",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Title (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="retreatday",
            name="title_ge",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="სათაური (GE)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description_en",
            field=models.TextField(
                blank=True, verbose_name="Full Description - on detail page (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description_ge",
            field=models.TextField(
                blank=True, verbose_name="სრული აღწერა - დეტალებზე (GE)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                null=True,
                verbose_name="იკონი (emoji)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ფასი/ინვესტიცია"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Title (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="about_title_ge",
            field=models.CharField(
                blank=True, default="გურანდა ლაზარაშვილი", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="chakras_title_ge",
            field=models.CharField(
                blank=True, default="რა მდგომარეობის დროს მომმართოთ?", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_copy_ge",
            field=models.CharField(
                blank=True,
                default="© 2026 Wonderlander Wellness. ყველა უფლება დაცულია.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_badge_ge",
            field=models.CharField(
                blank=True, default="✦ WONDERLANDER WELLNESS", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_btn1_en",
            field=models.CharField(blank=True, default="Book Now", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_btn1_ge",
            field=models.CharField(blank=True, default="ჩაწერა", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_btn2_ge",
            field=models.CharField(blank=True, default="სერვისები", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_creds_en",
            field=models.CharField(
                blank=True, default="MD, NLP, Holistic, Kundalini", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_creds_ge",
            field=models.CharField(
                blank=True,
                default="MD, NLP, Holistic, Kundalini",
                help_text="მძიმით გამოყოფილი",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_subtitle_en",
            field=models.TextField(
                blank=True, default="Hello. Thank you for your trust"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_subtitle_ge",
            field=models.TextField(blank=True, default="გამარჯობა. მადლობა ნდობისთვის"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_ge",
            field=models.TextField(
                blank=True, default="საკუთარ თავთან ჰარმონიული ურთიერთობა"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="home_cta_text_en",
            field=models.TextField(
                blank=True,
                default="The first step is a session. Results in 1-5 meetings.",
                verbose_name="Call-to-Action Text (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="home_cta_text_ge",
            field=models.TextField(
                blank=True,
                default="პირველი ნაბიჯი — ეს სესია. შედეგი 1-5 შეხვედრაში.",
                verbose_name="ქოლ-თუ-ექშენ ტექსტი (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="home_cta_title_en",
            field=models.CharField(
                blank=True,
                default="Ready for Transformation?",
                max_length=255,
                verbose_name="Call-to-Action Title (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="home_cta_title_ge",
            field=models.CharField(
                blank=True,
                default="მზად ხარ ტრანსფორმაციისთვის?",
                max_length=255,
                verbose_name="ქოლ-თუ-ექშენ სათაური (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="home_why_text1_en",
            field=models.TextField(
                blank=True,
                default="Unlike standard psychotherapy, we achieve results 10x faster. Most problems are resolved/goals achieved in 1-5 sessions.",
                verbose_name="Why Work with Me - Text 1 (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="home_why_text1_ge",
            field=models.TextField(
                blank=True,
                default="სტანდარტული ფსიქოთერაპიისგან განსხვავებით, შედეგებს ვიღებთ 10ჯერ უფრო სწრაფად. პრობლემათა უმრავლესობის გადაჭრა/მიზნების მიღწევა ხდება 1-5 სესიაში.",
                verbose_name="რატომ ჩემთან - ტექსტი 1 (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="home_why_text2_en",
            field=models.TextField(
                blank=True,
                default="Instead of exhausting conversations, we use unique methodology — Psycho-somatics, NLP, Hypnotherapy, Kundalini Activation, EFT, Art Therapy.",
                verbose_name="Why Work with Me - Text 2 (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="home_why_text2_ge",
            field=models.TextField(
                blank=True,
                default="სესიაზე დამღლელი საუბრების მაგივრად, ვიყენებთ უნიკალურ მეთოდოლოგიას — ფსიქო-სომატიკა, NLP, ჰიპნოთერაპია, კუნდალინი აქტივაცია, EFT, არტ თერაპია.",
                verbose_name="რატომ ჩემთან - ტექსტი 2 (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="home_why_title_en",
            field=models.CharField(
                blank=True,
                default="Why Work with Me?",
                max_length=255,
                verbose_name="Section 'Why Work with Me' Title (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="home_why_title_ge",
            field=models.CharField(
                blank=True,
                default="რატომ ჩემთან?",
                max_length=255,
                verbose_name="სექცია 'რატომ ჩემთან' სათაური (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="intro_tags_ge",
            field=models.TextField(
                blank=True,
                default="ფსიქო-სომატიკა, NLP, ჰიპნოთერაპია, კუნდალინი, EFT, არტ თერაპია, იოგა, მედიტაცია",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_bonuses_en",
            field=models.CharField(
                blank=True,
                default="Bonuses",
                max_length=100,
                verbose_name="Title 'Bonuses' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_bonuses_ge",
            field=models.CharField(
                blank=True,
                default="ბონუსები",
                max_length=100,
                verbose_name="სათაური 'ბონუსები' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_book_en",
            field=models.CharField(
                blank=True,
                default="Book",
                max_length=100,
                verbose_name="Button 'Book' (on retreats) (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_book_ge",
            field=models.CharField(
                blank=True,
                default="დაჯავშნა",
                max_length=100,
                verbose_name="ღილაკი 'დაჯავშნა' (რიტრიტებზე) (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_book_session_en",
            field=models.CharField(
                blank=True,
                default="Book a Session",
                max_length=100,
                verbose_name="Title 'Book a Session' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_book_session_ge",
            field=models.CharField(
                blank=True,
                default="დაჯავშნე სესია",
                max_length=100,
                verbose_name="სათაური 'დაჯავშნე სესია' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_booking_en",
            field=models.CharField(
                blank=True,
                default="Booking",
                max_length=50,
                verbose_name="Title 'Booking' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_booking_ge",
            field=models.CharField(
                blank=True,
                default="დაჯავშნა",
                max_length=50,
                verbose_name="სათაური 'დაჯავშნა' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_choose_chakra_en",
            field=models.CharField(
                blank=True,
                default="Click on the chakra where you feel the issue",
                max_length=255,
                verbose_name="Subtitle 'Choose Chakra' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_choose_chakra_ge",
            field=models.CharField(
                blank=True,
                default="დააჭირეთ ჩაკრას, რომელშიც პრობლემას გრძნობთ",
                max_length=255,
                verbose_name="ქვესათაური 'აირჩიეთ ჩაკრა' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_choose_course_en",
            field=models.CharField(
                blank=True,
                default="Choose the course that's right for you",
                max_length=255,
                verbose_name="Subtitle 'Choose Course' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_choose_course_ge",
            field=models.CharField(
                blank=True,
                default="აირჩიეთ თქვენთვის შესაფერი კურსი",
                max_length=255,
                verbose_name="ქვესათაური 'აირჩიეთ კურსი' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_course_en",
            field=models.CharField(
                blank=True,
                default="Course",
                max_length=50,
                verbose_name="Badge 'Course' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_course_ge",
            field=models.CharField(
                blank=True,
                default="კურსი",
                max_length=50,
                verbose_name="ბეიჯი 'კურსი' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_details_en",
            field=models.CharField(
                blank=True,
                default="Details →",
                max_length=50,
                verbose_name="Button 'Details' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_details_ge",
            field=models.CharField(
                blank=True,
                default="დეტალურად →",
                max_length=50,
                verbose_name="ღილაკი 'დეტალურად' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_early_bird_en",
            field=models.CharField(
                blank=True,
                default="Early Bird",
                max_length=50,
                verbose_name="Title 'Early Bird' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_early_bird_ge",
            field=models.CharField(
                blank=True,
                default="Early Bird",
                max_length=50,
                verbose_name="სათაური 'Early Bird' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_energy_centers_en",
            field=models.CharField(
                blank=True,
                default="Energy Centers",
                max_length=100,
                verbose_name="Badge 'Energy Centers' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_energy_centers_ge",
            field=models.CharField(
                blank=True,
                default="ენერგეტიკული ცენტრები",
                max_length=100,
                verbose_name="ბეიჯი 'ენერგეტიკული ცენტრები' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_enroll_en",
            field=models.CharField(
                blank=True,
                default="Enroll",
                max_length=100,
                verbose_name="Button 'Enroll' (on courses) (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_enroll_ge",
            field=models.CharField(
                blank=True,
                default="ჩაწერა",
                max_length=100,
                verbose_name="ღილაკი 'ჩაწერა' (კურსებზე) (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_guarantee_en",
            field=models.CharField(
                blank=True,
                default="110% Money-back Guarantee",
                max_length=100,
                verbose_name="Guarantee Text (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_guarantee_ge",
            field=models.CharField(
                blank=True,
                default="110% თანხის დაბრუნების გარანტია",
                max_length=100,
                verbose_name="გარანტიის ტექსტი (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_included_en",
            field=models.CharField(
                blank=True,
                default="What's Included",
                max_length=100,
                verbose_name="Title 'What's Included' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_included_ge",
            field=models.CharField(
                blank=True,
                default="ღირებულებაში შედის",
                max_length=100,
                verbose_name="სათაური 'ღირებულებაში შედის' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_let_start_en",
            field=models.CharField(
                blank=True,
                default="Let's Start",
                max_length=50,
                verbose_name="Button 'Let's Start' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_let_start_ge",
            field=models.CharField(
                blank=True,
                default="დავიწყოთ",
                max_length=50,
                verbose_name="ღილაკი 'დავიწყოთ' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_our_courses_en",
            field=models.CharField(
                blank=True,
                default="Our Courses",
                max_length=100,
                verbose_name="Title 'Our Courses' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_our_courses_ge",
            field=models.CharField(
                blank=True,
                default="ჩვენი კურსები",
                max_length=100,
                verbose_name="სათაური 'ჩვენი კურსები' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_popular_en",
            field=models.CharField(
                blank=True,
                default="Popular",
                max_length=50,
                verbose_name="Badge 'Popular' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_popular_ge",
            field=models.CharField(
                blank=True,
                default="პოპულარული",
                max_length=50,
                verbose_name="ბეიჯი 'პოპულარული' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_program_en",
            field=models.CharField(
                blank=True,
                default="Program",
                max_length=100,
                verbose_name="Title 'Program' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_program_ge",
            field=models.CharField(
                blank=True,
                default="პროგრამა",
                max_length=100,
                verbose_name="სათაური 'პროგრამა' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_regular_price_en",
            field=models.CharField(
                blank=True,
                default="Regular",
                max_length=50,
                verbose_name="Title 'Regular Price' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_regular_price_ge",
            field=models.CharField(
                blank=True,
                default="რეგულარული",
                max_length=50,
                verbose_name="სათაური 'რეგულარული ფასი' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_save_en",
            field=models.CharField(
                blank=True,
                default="Save",
                max_length=50,
                verbose_name="Text 'Save' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_save_ge",
            field=models.CharField(
                blank=True,
                default="დაზოგე",
                max_length=50,
                verbose_name="ტექსტი 'დაზოგე' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_select_en",
            field=models.CharField(
                blank=True,
                default="Select",
                max_length=100,
                verbose_name="Button 'Select' (on packages) (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_select_ge",
            field=models.CharField(
                blank=True,
                default="არჩევა",
                max_length=100,
                verbose_name="ღილაკი 'არჩევა' (პაკეტებზე) (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_submit_app_en",
            field=models.CharField(
                blank=True,
                default="Submit Application",
                max_length=100,
                verbose_name="Button 'Submit' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_submit_app_ge",
            field=models.CharField(
                blank=True,
                default="განაცხადის გაგზავნა",
                max_length=100,
                verbose_name="ღილაკი 'განაცხადის გაგზავნა' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_total_value_en",
            field=models.CharField(
                blank=True,
                default="Total Value",
                max_length=100,
                verbose_name="Text 'Total Value' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_total_value_ge",
            field=models.CharField(
                blank=True,
                default="ჯამური ღირებულება",
                max_length=100,
                verbose_name="ტექსტი 'ჯამური ღირებულება' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_what_learn_en",
            field=models.CharField(
                blank=True,
                default="What You'll Learn",
                max_length=100,
                verbose_name="Title 'What You'll Learn' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_what_learn_ge",
            field=models.CharField(
                blank=True,
                default="რას ისწავლი?",
                max_length=100,
                verbose_name="სათაური 'რას ისწავლი' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_whatsapp_btn_en",
            field=models.CharField(
                blank=True,
                default="Message on WhatsApp",
                max_length=100,
                verbose_name="Button 'WhatsApp' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_whatsapp_btn_ge",
            field=models.CharField(
                blank=True,
                default="WhatsApp-ზე დაწერა",
                max_length=100,
                verbose_name="ღილაკი 'WhatsApp' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_you_feel_en",
            field=models.CharField(
                blank=True,
                default="You feel...",
                max_length=100,
                verbose_name="Title 'You feel' (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="label_you_feel_ge",
            field=models.CharField(
                blank=True,
                default="შენ გრძნობ...",
                max_length=100,
                verbose_name="სათაური 'შენ გრძნობ' (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="nav_contact_ge",
            field=models.CharField(blank=True, default="კონტაქტი", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="nav_course_ge",
            field=models.CharField(blank=True, default="კურსები", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="nav_home_ge",
            field=models.CharField(blank=True, default="მთავარი", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="nav_retreat_ge",
            field=models.CharField(blank=True, default="ბალი", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="nav_review_ge",
            field=models.CharField(blank=True, default="უკუკავშირი", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="navbar_cta_en",
            field=models.CharField(
                blank=True,
                default="Book Now",
                max_length=50,
                verbose_name="ნავბარის ღილაკი (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="navbar_cta_ge",
            field=models.CharField(
                blank=True,
                default="ჩაწერა",
                max_length=50,
                verbose_name="ნავბარის ღილაკი (GE)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="reviews_empty_text_ge",
            field=models.CharField(
                blank=True, default="უკუკავშირები ჯერ არ დამატებულა.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="reviews_title_ge",
            field=models.CharField(
                blank=True, default="რას ამბობენ ჩვენზე", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="services_title_ge",
            field=models.CharField(
                blank=True, default="ინვესტიცია საკუთარ თავში", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_title_en",
            field=models.CharField(
                blank=True, default="Wonderlander Wellness", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_title_ge",
            field=models.CharField(
                blank=True, default="Wonderlander Wellness", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat1_label_ge",
            field=models.CharField(
                blank=True, default="უფრო სწრაფი შედეგი", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat1_num",
            field=models.CharField(blank=True, default="10x", max_length=20),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat2_label_ge",
            field=models.CharField(
                blank=True, default="სესია მიზნისთვის", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat2_num",
            field=models.CharField(blank=True, default="1-5", max_length=20),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat3_label_ge",
            field=models.CharField(
                blank=True, default="ენერგეტ. ცენტრი", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat3_num",
            field=models.CharField(blank=True, default="7", max_length=20),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat4_label_ge",
            field=models.CharField(blank=True, default="სამოქმ. გეგმა", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="stat4_num",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
