# Generated by Django 6.0.5 on 2026-07-01 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_botsettings_admin_chat_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetreatActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="საათი (მაგ: 09:00)"
                    ),
                ),
                (
                    "title_ge",
                    models.CharField(max_length=255, verbose_name="აქტივობა (GE)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Activity (EN)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="თანმიმდევრობა"
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.retreatday",
                        verbose_name="დღე",
                    ),
                ),
            ],
            options={
                "verbose_name": "აქტივობა",
                "verbose_name_plural": "აქტივობები",
                "ordering": ["order", "time"],
            },
        ),
    ]
